### ISSUE TITLE
When can we expect the new version?

### ISSUE THREAD

**Issue by markaswift** [Jackysi/AdvancedTomato-V2#10]
Howdy,

I noticed there is a new version available on Shibby's website. When can we expect the fantastic advanced tomato to be available for general download?

**Comment by Jackysi** [comment]
Gosh, this is BUGS & ISSUE tracking NOT SUPPORT OR FORUM! Stop posting questions like that here... http://www.linksysinfo.org/index.php?threads/advancedtomato-v2-gui-based-on-shibbys-mod.70254/page-5

**Comment by markaswift** [comment]
Keep me your kickers on, I never knew there was a forum, gosh! :-/

**Comment by Jackysi** [comment]
Man even so this is Github issues section. You could use contact on web site or what ever just not this section.

**Comment by markaswift** [comment]
Okay will do, apologies… At least my ‘bug’ contained a compliment :-)

**Comment by Jackysi** [comment]
Excuse me for my temper but I really have enough of people not reading stuff lolz... We web site masters write stuff so you read them not that it's all ignored and people follow their own rules. I set the rules here lolz. New version is finished but compilation fails under all distros which means that it will be postponed indefinitely. I don't have required knowledge to find out which of packages is the problem so without Shibby's help i'm in dark. Shibby however seems to be busy at the time so everything is delayed. This project doesn't pay me so even with that in mind asking for updates is rude.
