### ISSUE TITLE
Virtual Wireless Won't "Save"

### ISSUE THREAD

**Issue by rgvalin** [Jackysi/AdvancedTomato-V2#11]
The following problem continually happens on two, separate systems (2 separate routers in physically separate locations/ISPs).

I'm using Tomato Firmware 1.28.0000 MIPSR2-2.9-131 K26AC USB AIO-64K flashed to ASUS RT-AC66U routers. Both machines are Windows 10 with router access via Microsoft Edge.  Setup of a guest network on br1 and the VLAN bridge to br1 works as advertised. But when trying to add virtual wireless interfaces, the system hangs at the final "save" step (remains in "Saving …" mode forever). Adding security and viewing the "new" connection setup appears normal on the "Overview" splash page. When I navigate out of the Virtual Wireless page (regardless of how long "Saving ..." shows), nothing is set up. Needless to say, I've tried this in both physically separate locations with the same results. Soft/hard reboots of the routers has no effect.

I'm very impressed with Tomato and if need be will go to the latest Shibby version to correct this fault — but am I missing something? Thanks in advance for your help!

**Comment by Jackysi** [comment]
I can't say for sure, can you try Shibby and see what happends? Its possible there is a bug in my interface but I need someone to test it. I can't do it on my own because I don't own AC66U.

**Comment by rgvalin** [comment]
Jacky -- thanks for your quick response!
I flashed my AC66U with the latest Shibby -- everything works as advertised (including virtual wireless on the first try). While I prefer your GUI, I need the virtual wireless to work, so I'll be sticking with Shibby until/unless AT is updated to correct the problem. Please let me know if AT gets updated.  Thanks again!

**Comment by Jackysi** [comment]
I can't update/fix the issue without any information about the bug :). I attempted to reproduce your issue but it saved and worked fine for me on RT-N66U. But okay thx for report anyway...
