### ISSUE TITLE
Mobile version

### ISSUE THREAD

**Issue by maciejby** [Jackysi/AdvancedTomato-V2#2]
On WVGA phone interface is so small. Please consider responsive web design.

**Comment by Jackysi** [comment]
This interface can't be adapted well to fit small screens. There is just too much information, tables, etc... I tried but its too much work. I simply have no time to do all the work on my own.

**Comment by maciejby** [comment]
Understand. Take a look 
![28-05-2013-13-51-54](https://cloud.githubusercontent.com/assets/10815762/6026793/c4e32dba-abdd-11e4-8be3-3103f3cb255b.jpg)

**Comment by Jackysi** [comment]
That looks awesome, is this like a mobile version?

**Comment by Jackysi** [comment]
That is
