### ISSUE TITLE
Missing IPv6 "6rd relay"

### ISSUE THREAD

**Issue by arigit** [Jackysi/AdvancedTomato-V2#3]
Shibby's mod supports "6rd Relay" as one of the options for "IPv6 Service Type".
He added support for this in version 1.20.

Advanced Tomato 2.5-124 K26 USB AIO claims to be based on Shibby 1.24 so it should support this.

(Using 2.5-124 K26 USB AIO, on E4200 hardware v1)

Can you please add support for configuring 6rd Relay in the IPv6 option? There are quite a few cable operators that started IPv6 trials using 6rd.

Thanks

Reference:
Screenshots of Shibby's web GUI:
https://imgur.com/gallery/jtg0L

See also:
https://forums.sonic.net/viewtopic.php?f=13&t=1877&start=50#p12109

**Comment by Jackysi** [comment]
I apologize for late response, this was added in latest GUI version. This update is not yet released as firmware image but it is committed to GIT.

**Comment by arigit** [comment]
Thanks for this!!

Waiting for the new release (2.6-127) to be made available for Cisco/Linksys E4200 to test this out.
