### ISSUE TITLE
FTP

### ISSUE THREAD

**Issue by xvortex** [Jackysi/AdvancedTomato-V2#4]
Disabling NGINX also disables FTP menu.

**Comment by Jackysi** [comment]
You mean at compile time right? I will fix that soon. Thanks for letting me know.
I still haven't figured out the way to re-order menu to make more sense.

**Comment by xvortex** [comment]
yes. I'm using a config without NGINX but with FTP enabled.
I've managed to avoid this by moving ftp cut-out section back to usb section.

**Comment by Jackysi** [comment]
This has been fixed in latest release
