### ISSUE TITLE
IP Traffic graphs showing wrong units?

### ISSUE THREAD

**Issue by markaswift** [Jackysi/AdvancedTomato-V2#7]
Hello,

I'm running the latest version (131) on my R7000.

The issue I'm having is that the units on the IP Traffic graphs do not seem to match the actual data throughput. When running a speedtest from my Macbook (14Mbps up, 1Mbps down) the graphs do not show more than 7 KB/s...

What could cause this?

**Comment by Jackysi** [comment]
Apologies for late response, this is not a support section and I don't offer firmware but only GRAPHICAL INTERFACE. The issue must be somewhere in the firmware itself. This function works fine for me and no one else reported this sort of issue
