### ISSUE TITLE
Can't upload custom captive portal screen

### ISSUE THREAD

**Issue by sb56637** [Jackysi/AdvancedTomato-V2#9]
Hi, I'd like to report a bug. It appears impossible to upload a file in the Captive Portal section. If the file is fairly large (image embedded into the HTML) it throws an error "Somthing went wrong... Invalid file". And even if it's an extremely small HTML file it says "500 Unknown - Read error"

Thanks a lot for developing AdvancedTomato!

**Comment by Jackysi** [comment]
I'm not sure what could this be, though this is not GUI related issue. My work is based on Shibby's firmware and my work is only graphical interface. The firmware itself accepts file and if something was wrong it would issue the error above. My point is I can't influence this behaviour from my work.
